ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- " lxc "

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample
- Privilege Escalation
- Remote Code Execution
- Command Injection
- SQL Injection
- Cross Site Scripting

PRODUCT_KEYWORDS_I:
- sudo

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample
- sudo
